/* eslint-disable @next/next/no-page-custom-font */
import 'style/globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Stroke Detection',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
        {children}
        </div>
      </body>
    </html>
  )
}
